// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv84xT29sezYD8hwM83Ob6ynpRvMSPl_Q',
    appId: '1:949526283494:web:a7ccb57096ca382d03a727',
    messagingSenderId: '949526283494',
    projectId: 'unibus-4614a',
    authDomain: 'unibus-4614a.firebaseapp.com',
    storageBucket: 'unibus-4614a.firebasestorage.app',
    measurementId: 'G-DV1TN918JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqq2uZd2W36gIwljTRvKEQAVQ78x-P-QI',
    appId: '1:949526283494:android:942ca383915ac6b903a727',
    messagingSenderId: '949526283494',
    projectId: 'unibus-4614a',
    storageBucket: 'unibus-4614a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv84xT29sezYD8hwM83Ob6ynpRvMSPl_Q',
    appId: '1:949526283494:web:d9b2f5970780bf4d03a727',
    messagingSenderId: '949526283494',
    projectId: 'unibus-4614a',
    authDomain: 'unibus-4614a.firebaseapp.com',
    storageBucket: 'unibus-4614a.firebasestorage.app',
    measurementId: 'G-Q6730KM5PX',
  );
}
